# Site Settings
lang: en
title: 
baseurl: ""
url: "https://aweblayer.github.io/"

theme: bulma-clean-theme

paginate: 5
paginate_path: "/blog/page:num"

author:
  name: aweblayer
  email: "awebayer@gmail.com"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "aweblayer"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: false

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  style: compressed
  source_dir: _sass

markdown: kramdown
highlighter: rouge