# Site Settings
lang: en
title: Muggle Programmer
url: "https://aweblayer.github.io/"
baseurl: ""
description: Blog

# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: aweblayer

author:
  name: aweblayer
  email: "awebayer@gmail.com"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "aweblayer"
      layout: post
      image: https://via.placeholder.com/800x400
      show_sidebar: false

plugins:
  - github-pages
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  style: compressed
  source_dir: _sass

markdown: kramdown
highlighter: rouge